# Generated by Django 4.2.23 on 2025-08-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(choices=[('L', 'Large'), ('XXL', 'Extra Extra Large'), ('S', 'Small'), ('XL', 'Extra Large'), ('XS', 'Extra Small'), ('M', 'Medium')], default='M', max_length=4)),
                ('price', models.IntegerField()),
                ('composition', models.CharField(max_length=30)),
                ('stock', models.IntegerField(null=True)),
                ('inStock', models.BooleanField()),
                ('code', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('default_image', models.ImageField(blank=True, unique=True, upload_to='images/default')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
            options={
                'verbose_name_plural': 'Dresses',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/variants')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dress')),
            ],
        ),
    ]
