# Generated by Django 5.2.3 on 2025-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dress',
            options={'verbose_name_plural': 'Dresses'},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='var',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(default=1, upload_to='images/variants'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dress',
            name='inStock',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dress',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='M'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
