# Generated by Django 4.2.23 on 2025-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='size',
        ),
        migrations.AlterField(
            model_name='dress',
            name='default_image',
            field=models.ImageField(unique=True, upload_to='default'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, upload_to='variants'),
        ),
    ]
