# Generated by Django 4.2.23 on 2025-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_dress_size_alter_dress_default_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=3)),
                ('dress', models.ManyToManyField(to='home.dress')),
            ],
        ),
    ]
