# Generated by Django 5.2.4 on 2025-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_dress_options_remove_variant_var_variant_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='dress',
            name='default_image',
            field=models.ImageField(blank=True, unique=True, upload_to='images/default'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='dress',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/variants'),
        ),
    ]
