# Generated by Django 4.2.23 on 2025-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='dress',
        ),
        migrations.AddField(
            model_name='dress',
            name='size',
            field=models.ManyToManyField(to='home.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
