# Generated by Django 4.2.23 on 2025-08-31 13:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_size_dress_dress_size_alter_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='hex',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
