# Generated by Django 4.2.23 on 2025-08-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_variant_code_variant_hex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='hex',
            new_name='colorHex',
        ),
        migrations.AlterField(
            model_name='variant',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='variants'),
        ),
    ]
